#!/bin/sh

. $NTTOOLS

set -e

OPTIONS=$1
shift
OUTPUT=$1
shift

XOPTS="-b -c"

case "E$OPTIONS" in
  *x*)
    OPCHAR='*'
   if [ $# = 0 ]; then
      TMPDIR=TMP$$.d
      rm -rf $TMPDIR >/dev/null 2>/dev/null || :
      mkdir $TMPDIR
      do_cmd wlib -x -d=$TMPDIR `fixpath $OUTPUT`
      (
        cd $TMPDIR
        for a in *
        do
          BASE=`echo $a | sed -e 's/\.[^.]$//'`
          mv $a ../$BASE.o
        done
      )
      rm -rf $TMPDIR >/dev/null 2>/dev/null || :
      exit 0
   fi
  ;;

  *d*)
    OPTCHAR='-'
  ;;

  *r*)
    OPCHAR='-+'
  ;;

  *q*)
    OPCHAR='+'
  ;;
esac

XFILE=TMP$$.l

rm $XFILE 2>/dev/null 1>/dev/null || :

OPTS=
for a in "$@"
do
  OPTS="$OPTS $OPCHAR$a"
done

echo >$XFILE "$OPTS"

do_cmd wlib $XOPTS `fixpath $OUTPUT` @$XFILE

if [ $CLEANUP = yes ]; then
  if [ -f $XFILE ]; then
    rm $XFILE
  fi
fi
