#!/bin/sh

. $NTTOOLS

set -e

OPTIONS=$1
shift
OUTPUT=$1
shift

XFILE=TMP$$.l

rm $XFILE 2>/dev/null 1>/dev/null || :

OPTS=
for a in "$@"
do
  OPTS="$OPTS +$a"
done

echo >$XFILE $OPTS

do_cmd wlib -b -c $OUTPUT @$XFILE

if [ $CLEANUP = yes ]; then
  if [ -f $XFILE ]; then
    rm $XFILE
  fi
fi
