SRCDIR=@srcdir@
VPATH=@srcdir@:@srcdir@/../..:../..
PREFLAGS=-I$(SRCDIR) -I$(SRCDIR)/../.. -I../..
CFLAGS=$(PREFLAGS) $(OTHERFLAGS) @DEFS@

FILES=image.o font.o quant.o lzw.o togif.o

image.a: $(FILES)
	-rm -f image.a
	ar cq image.a $(FILES)
	-@RANLIB@ image.a

clean:
	-rm -f *.o *.a

pike: image.a
	cd ../..; make

pure: image.a
	cd ../..; make pure


depend:
	gcc -MM $(PREFLAGS) $(SRCDIR)/*.c | $(FIXDEP) $(SRCDIR)

