.\" $Id: pike.1,v 1.26 2005/12/29 10:45:39 grubba Exp $
.\" name section last-modified title section-name product/status architecture
.ds ]L Pike
.TH pike 1 "$Date: 2005/12/29 10:45:39 $" Pike "Pike Manual" Pike
.\" On Solaris ]L will contain "Last modified $Date: 2005/12/29 10:45:39 $"
.\" while HPUX uses ]L to contain "Pike".
.\" On OSF/1 ]L will already contain the wanted string.
.if !\*(]LPike .ds ]L $Date: 2005/12/29 10:45:39 $ \" Solaris nroff
.\" Major (mj) and minor (mn) version of Pike
.nr mj 7
.nr mn 6
.SH NAME
pike \- pike compiler and interpreter
.SH SYNOPSIS
.B pike
[
.B \-driver\-options ...
] [
.IR script
[
.B script\-arguments ...
] ]
.SH DESCRIPTION
Compiler and interpreter for the Pike programming language.
.SH OPTIONS
The following options are supported by the loader:
.TP
.B \-a
Increase the debug level of the peep-hole optimizer with 1 (debug).
.TP
.BI \-a num
Set the debug level of the peep-hole optimizer to
.I num
(debug).
.TP
.BI \-D symbol
Define the preprocessor symbol
.I symbol
to 1.
.TP
.BI \-D symbol=value
Define the preprocessor symbol
.I symbol
to
.I value.
.TP
.B \-d
Increase the debug level with 1 (debug).
.TP
.BI \-d num
Set the debug level to
.I num
(debug).
.TP
.B \-dc
Increase the debug level of the Pike compiler (debug).
.TP
.B \-dg
Resets the debug malloc at every garbage collection (debug).
.TP
.B \-dp
Turns off the peep hole optimization (debug).
.TP
.B \-ds
Debug signals (debug).
.TP
.B \-dt
Turn off tail recursion optimization (debug).
.TP
.B \-dT
Enable extra checks in the thread library, e.g. mutex sanity checks (debug).
.TP
.B \-l
Increase the debug level of the global optimizer with 1 (debug).
.TP
.BI \-l num
Set the debug level of the global optimizer to
.I num
(debug).
.TP
.BI \-m master_program
Use
.I master_program
instead of the ordinary master program.
.TP
.BI \-q num
End execution after executing
.I num
Pike instructions.
.TP
.BI \-s num
Set Pike stack size to
.I num
(minimum is 256).
.TP
.B \-t
Increase the level of runtime trace with 1 (debug).
.TP
.BI \-t num
Set the level of runtime trace to
.I num
(debug).
.TP
.B \-tg
Log the gc runs to stderr.
.TP
.B \-p
Increase the level of profiling with 1 (debug).
.TP
.BI \-p num
Set the level of profiling to
.I num
(debug).
.TP
.B \-rt
Turn on runtime checking of arguments to function calls, and soft casts.
.TP
.B \-rT
Turn on
.B #pragma strict_types
for all files.
.LP
The following options are supported by the default master program:
.TP
.B \-h, \-\-help,
Print help message and exit.
.TP
.BI \-e expr, \-\-execute =expr
Execute
.I expr
and exit.
.TP
.B \-E, \-\-preprocess
Just run the preprocessor.
.TP
.BI \-I dir, \-\-include\-path =dir
Append
.I dir
to the include path.
.TP
.BI \-M dir, \-\-modue\-path =dir
Append
.I dir
to the module path.
.TP
.BI \-P dir, \-\-program\-path =dir
Append
.I dir
to the program path.
.TP
.B \-v, \-\-version
Print version of Pike and exit.
.TP
.BI \-V major.minor, \-\-compat =major.minor
Set the compatibility version to Pike version
.I major.minor.
.TP
.B \-w, \-\-warnings
Enable warnings.
.TP
.B \-W, \-\-woff, \-\-no\-warnings
Disable warnings.
.TP
.B \-\-assembler\-debug
Set the peephole optimizer debug level (debug).
.TP
.B \-\-compiler\-trace
Turn on tracing of the Pike compiler (debug).
.TP
.B \-\-debug
Increase or set the debug level (debug).
.TP
.BI \-\-debug\-without =feature
Hide 
.I feature
from the resolver (debug).
.TP
.B \-\-dumpversion
Print the Pike version number to stderr, e.g. "7.8.10\\n"
.TP
.B \-\-features
List some of the features that are enabled in this Pike binary
and exit (debug).
.TP
.B \-\-info
Show various information about this Pike installation and exit (debug).
.TP
.B \-\-optimizer\-debug
Set the global optimizer debug level (debug).
.TP
.B \-\-show\-paths
Show the paths pike will use and exit (debug).
.TP
.B \-\-trace
Increase the trace level (debug).
.TP
.BI \-\-trace =num
Set the trace level to
.I num
(debug).
.SH OPERANDS
The following operand is supported:
.TP
.I script
A path to a script written in Pike to be compiled and then executed.
Everything on the commandline after the script is passed as arguments
to the script.
.LP
If no script is specified, pike will start in interactive- (Hilfe) mode.
.SH REGISTRY KEYS
On NT, Pike is affected by the following keys in the registry:

.B HKEY_CURRENT_USER\eSoftware\ePike\e\n(mj.\n(mn\ePIKE_MASTER
.B HKEY_LOCAL_MACHINE\eSoftware\ePike\e\n(mj.\n(mn\ePIKE_MASTER
.RS
Specifies the name of the master program (overridden by
.BI \-m master_program
).
.RE
.SH ENVIRONMENT
Pike is affected by the following environment variables:
.TP
.B PIKE_MASTER
Specifies the name of the master program (overridden by
.BI \-m master_program
).
.LP
Depending on operating system Pike may be affected by the following
environment variables:
.TP
.B LC_ALL
Overrides the other LC_* variables.
.TP
.B LC_COLLATE
Specifies the character collation sequence.
.TP
.B LC_CTYPE
Specifies the character classification.
.TP
.B LC_MESSAGES
Specifies the language of the system messagedatabase.
.TP
.B LC_NUMERIC
Specifies the decimal and thousand delimiters.
.TP
.B LC_TIME
Specifies the date and time formats.
.LP
The default master program is affected by the following environment variables:
.TP
.B PIKE_INCLUDE_PATH
List of directories separated with colon (:), to search for include-files.
.TP
.B PIKE_PROGRAM_PATH
List of directories separated with colon (:), to search for program-files.
.TP
.B PIKE_MODULE_PATH
List of directories separated with colon (:), to search for modules.
.TP
.B LONG_PIKE_ERRORS
If set disables truncation of paths in backtraces.
.TP
.B SHORT_PIKE_ERRORS
If set and
.B LONG_PIKE_ERRORS
is not set, truncates paths to just the filename in backtraces.
.TP
.B PIKE_BACKTRACE_LEN
The maximum number of elements in arrays to describe in backtraces.
.LP
Note that the above environment variables have effect before the default
master program attempts to load the
.BR Getopt (3P)
module, which occurrs before the master program arguments are parsed.
.SH EXIT STATUS
The following exit values are returned:
.TP
.B 0
Successfull completion.
.TP
.B >0
An error occurred. See output on stderr (fd #2) for reason.
.SH FILES
.\" Set the paragraph distance to zero
.PD 0
.\" Basedirectory (bd)
.ds bd @PREFIX@
.TP 24
.B \*(bd/lib/pike/pike\n(mj.\n(mn/master.pike
default master program
.TP
.B \*(bd/lib/pike/pike\n(mj.\n(mn/modules/*
default module directory
.TP
.B \*(bd/lib/pike/pike\n(mj.\n(mn/?.?/*
backward compatibility modules
.TP
.B \*(bd/lib/pike/pike\n(mj.\n(mn/include/*
pike include files
.TP
.B \*(bd/tools/pike.el
emacs fontlock definitions for pike-mode
.TP
.B \*(bd/include/pike/pike\n(mj.\n(mn/*
C-include files
.TP
.B \*(bd/man/*
manual pages for pike
.\" Restore the paragraph distance
.PD
.SH SEE ALSO
.BR hilfe (1),
.BR Getopt (3P),
.BR environ (5)
.\" Force a linebreak
.sp 0vu
.I Pike Programming Tutorial
.sp 0vu
.I Pike Reference Manual
