/*
|| This file is part of Pike. For copyright information see COPYRIGHT.
|| Pike is distributed under GPL, LGPL and MPL. See the file COPYING
|| for more information.
|| $Id: gdkeventstrings.h,v 1.1 2005/07/28 15:22:33 nilsson Exp $
*/

STRING(2button_press);
STRING(3button_press);
STRING(atom);
STRING(button);
STRING(button_press);
STRING(button_release);
STRING(client);
STRING(configure);
STRING(context);
STRING(count);
STRING(data);
STRING(data_format);
STRING(delete);
STRING(destroy);
STRING(detail);
STRING(deviceid);
STRING(drag_enter);
STRING(drag_finished);
STRING(drag_leave);
STRING(drag_motion);
STRING(drag_start);
STRING(drag_status);
STRING(drop_finished);
STRING(drop_start);
STRING(enter_notify);
STRING(expose);
STRING(focus);
STRING(focus);
STRING(height);
STRING(in);
STRING(is_hint);
STRING(key_press);
STRING(key_release);
STRING(keyval);
STRING(leave_notify);
STRING(map);
STRING(mapping);
STRING(message_type);
STRING(mode);
STRING(motion);
STRING(noexpose);
STRING(nothing);
STRING(pressure);
STRING(property);
STRING(property);
STRING(proximity_in);
STRING(proximity_out);
STRING(requestor);
STRING(selection);
STRING(selection_clear);
STRING(selection_notify);
STRING(selection_request);
STRING(send_event);
STRING(state);
STRING(target);
STRING(time);
STRING(type);
STRING(unmap);
STRING(visibility);
STRING(width);
STRING(x);
STRING(x_root);
STRING(xtilt);
STRING(y);
STRING(y_root);
STRING(ytilt);
