// Automatically generated by "doc-pikeref.pike" from "pangoattrlist.pre".
// Do NOT edit.

//! A PangoAttrList.
//!
//!

Pango.AttrList copy( );
//! Copy the list.
//!
//!

protected void create( );
//! Create a new empty attribute list.
//!
//!
