// Automatically generated by "doc-pikeref.pike" from "gdkevent.pre".
// Do NOT edit.

//! Gdk events.
//!
//!


protected mixed _index( string ind );
//! Return an index.
//!
//!


mapping cast( string to );
//! Cast to different types.
//!
//!
