SRCDIR=@srcdir@
VPATH=@srcdir@:@srcdir@/../..:../..
PREFLAGS=-I. -I$(SRCDIR) -I$(SRCDIR)/../.. -I../..
CFLAGS=$(PREFLAGS) $(OTHERFLAGS)

FILES=gdbmmod.o
LIB=gdbmmod.a

$(LIB): $(FILES)
	-rm -f $(LIB)
	ar cq $(LIB) $(FILES)
	-@RANLIB@ $(LIB)
	echo >linker_options @LIBS@

clean:
	-rm -f *.o *.a

depend:
	gcc -MM $(PREFLAGS) $(SRCDIR)/*.c | $(FIXDEP) $(SRCDIR)
