#pike 7.9

#if constant(Crypto.Hash)

//! Encryption and MAC algorithms used in SSL - Compat with Pike 7.8.

//! @decl inherit predef::SSL.Cipher
//! Based on the current SSL.Cipher.

inherit SSL.Cipher : Cipher;

//! Pike 7.8 compatibility version of @[predef::SSL.Cipher.DES].
class DES
{
  //! Based on the current SSL.Cipher.DES.
  inherit Cipher::DES;

  //! create() used to be visible.
  //!
  //! @seealso
  //!   @[::create()]
  void create()
  {
    ::create();
  }
}

//! Pike 7.8 compatibility version of @[predef::SSL.Cipher.DES3].
class DES3
{
  //! Based on the current SSL.Cipher.DES3.
  inherit Cipher::DES3;

  //! create() used to be visible.
  //!
  //! @seealso
  //!   @[::create()]
  void create()
  {
    ::create();
  }
}

//! Pike 7.8 compatibility version of @[predef::SSL.Cipher.IDEA].
class IDEA
{
  //! Based on the current SSL.Cipher.IDEA.
  inherit Cipher::IDEA;

  //! create() used to be visible.
  //!
  //! @seealso
  //!   @[::create()]
  void create()
  {
    ::create();
  }
}

//! Pike 7.8 compatibility version of @[predef::SSL.Cipher.AES].
class AES
{
  //! Based on the current SSL.Cipher.AES.
  inherit Cipher::AES;

  //! create() used to be visible.
  //!
  //! @seealso
  //!   @[::create()]
  void create()
  {
    ::create();
  }
}

//! Pike 7.8 compatibility version of Diffie-Hellman parameters.
class DHParameters
{
  Gmp.mpz p, g, order;
  //!

  /* Default prime and generator, taken from the ssh2 spec:
   *
   * "This group was taken from the ISAKMP/Oakley specification, and was
   *  originally generated by Richard Schroeppel at the University of Arizona.
   *  Properties of this prime are described in [Orm96].
   *...
   *  [Orm96] Orman, H., "The Oakley Key Determination Protocol", version 1,
   *  TR97-92, Department of Computer Science Technical Report, University of
   *  Arizona."
   */

  /* p = 2^1024 - 2^960 - 1 + 2^64 * floor( 2^894 Pi + 129093 ) */

  protected Gmp.mpz orm96() {
    p = Gmp.mpz("FFFFFFFF FFFFFFFF C90FDAA2 2168C234 C4C6628B 80DC1CD1"
                "29024E08 8A67CC74 020BBEA6 3B139B22 514A0879 8E3404DD"
                "EF9519B3 CD3A431B 302B0A6D F25F1437 4FE1356D 6D51C245"
                "E485B576 625E7EC6 F44C42E9 A637ED6B 0BFF5CB6 F406B7ED"
                "EE386BFB 5A899FA5 AE9F2411 7C4B1FE6 49286651 ECE65381"
                "FFFFFFFF FFFFFFFF", 16);
    order = (p-1) / 2;

    g = Gmp.mpz(2);

    return this;
  }

  protected void create(object ... args) {
    switch (sizeof(args))
    {
    case 0:
      orm96();
      break;
    case 3:
      [p, g, order] = args;
      break;
    default:
      error( "Wrong number of arguments.\n" );
    }
  }
}

//! Pike 7.8 compatibility version of @[predef::SSL.Cipher.DHKeyExchange].
class DHKeyExchange
{
  //! Based on the current SSL.Cipher.DHKeyExchange.
  inherit Cipher::DHKeyExchange;

  //! create() used to be visible.
  //!
  //! @seealso
  //!   @[::create()]
  void create(DHParameters p)
  {
    ::create(p);
  }
}

#else // constant(Crypto.Hash)
constant this_program_does_not_exist = 1;
#endif
