import GL;
import GLU;
#if constant(GLUT)
import GLUT;
#endif

#define glColor3b(R,G,B) glColor(R,G,B)
#define glColor3d(R,G,B) glColor(R,G,B)
#define glColor3f(R,G,B) glColor(R,G,B)
#define glColor3i(R,G,B) glColor(R,G,B)
#define glColor3s(R,G,B) glColor(R,G,B)
#define glColor3ub(R,G,B) glColor(R,G,B)
#define glColor3ui(R,G,B) glColor(R,G,B)
#define glColor3us(R,G,B) glColor(R,G,B)

#define glColor4b(R,G,B,A) glColor(R,G,B,A)
#define glColor4d(R,G,B,A) glColor(R,G,B,A)
#define glColor4f(R,G,B,A) glColor(R,G,B,A)
#define glColor4i(R,G,B,A) glColor(R,G,B,A)
#define glColor4s(R,G,B,A) glColor(R,G,B,A)
#define glColor4ub(R,G,B,A) glColor(R,G,B,A)
#define glColor4ui(R,G,B,A) glColor(R,G,B,A)
#define glColor4us(R,G,B,A) glColor(R,G,B,A)

#define glColor3bv(V) glColor(V)
#define glColor3dv(V) glColor(V)
#define glColor3fv(V) glColor(V)
#define glColor3iv(V) glColor(V)
#define glColor3sv(V) glColor(V)
#define glColor3ubv(V) glColor(V)
#define glColor3uiv(V) glColor(V)
#define glColor3usv(V) glColor(V)

#define glColor4bv(V) glColor(V)
#define glColor4dv(V) glColor(V)
#define glColor4fv(V) glColor(V)
#define glColor4iv(V) glColor(V)
#define glColor4sv(V) glColor(V)
#define glColor4ubv(V) glColor(V)
#define glColor4uiv(V) glColor(V)
#define glColor4usv(V) glColor(V)

#define glEvalCoord1d(U) glEvalCoord(U)
#define glEvalCoord1f(U) glEvalCoord(U)

#define glEvalCoord2d(U,V) glEvalCoord(U,V)
#define glEvalCoord2f(U,V) glEvalCoord(U,V)

#define glEvalCoord1dv(U) glEvalCoord(U)
#define glEvalCoord1fv(U) glEvalCoord(U)
#define glEvalCoord2dv(U) glEvalCoord(U)
#define glEvalCoord2fv(U) glEvalCoord(U)

#define glEvalPoint1(I) glEvalPoint(I)
#define glEvalPoint2(I,J) glEvalPoint(I,J)

#define glFogf(N,P) glFog(N,P)
#define glFogi(N,P) glFog(N,P)
#define glFogfv(N,P) glFog(N,P)
#define glFogiv(N,P) glFog(N,P)

#define glIndexd(C) glIndex(C)
#define glIndexf(C) glIndex(C)
#define glIndexi(C) glIndex(C)
#define glIndexs(C) glIndex(C)
#define glIndexub(C) glIndex(C)

#define glLightf(L,N,P) glLight(L,N,P)
#define glLighti(L,N,P) glLight(L,N,P)
#define glLightfv(L,N,P) glLight(L,N,P)
#define glLightiv(L,N,P) glLight(L,N,P)

#define glLightModelf(N,P) glLightModel(N,P)
#define glLightModeli(N,P) glLightModel(N,P)
#define glLightModelfv(N,P) glLightModel(N,P)
#define glLightModeliv(N,P) glLightModel(N,P)

#define glLoadMatrixd(M) glLoadMatrix(M)
#define glLoadMatrixf(M) glLoadMatrix(M)

#define glMaterialf(F,N,P) glMaterial(F,N,P)
#define glMateriali(F,N,P) glMaterial(F,N,P)
#define glMaterialfv(F,N,P) glMaterial(F,N,P)
#define glMaterialiv(F,N,P) glMaterial(F,N,P)

#define glMultMatrixd(M) glMultMatrix(M)
#define glMultMatrixf(M) glMultMatrix(M)

#define glNormal3b(X,Y,Z) glNormal(X,Y,Z)
#define glNormal3d(X,Y,Z) glNormal(X,Y,Z)
#define glNormal3f(X,Y,Z) glNormal(X,Y,Z)
#define glNormal3i(X,Y,Z) glNormal(X,Y,Z)
#define glNormal3s(X,Y,Z) glNormal(X,Y,Z)

#define glNormal3bv(V) glNormal(V)
#define glNormal3dv(V) glNormal(V)
#define glNormal3fv(V) glNormal(V)
#define glNormal3iv(V) glNormal(V)
#define glNormal3sv(V) glNormal(V)

#define glRasterPos2d(X,Y) glRasterPos(X,Y)
#define glRasterPos2f(X,Y) glRasterPos(X,Y)
#define glRasterPos2i(X,Y) glRasterPos(X,Y)
#define glRasterPos2s(X,Y) glRasterPos(X,Y)

#define glRasterPos3d(X,Y,Z) glRasterPos(X,Y,Z)
#define glRasterPos3f(X,Y,Z) glRasterPos(X,Y,Z)
#define glRasterPos3i(X,Y,Z) glRasterPos(X,Y,Z)
#define glRasterPos3s(X,Y,Z) glRasterPos(X,Y,Z)

#define glRasterPos4d(X,Y,Z,W) glRasterPos(X,Y,Z,W)
#define glRasterPos4f(X,Y,Z,W) glRasterPos(X,Y,Z,W)
#define glRasterPos4i(X,Y,Z,W) glRasterPos(X,Y,Z,W)
#define glRasterPos4s(X,Y,Z,W) glRasterPos(X,Y,Z,W)

#define glRasterPos2dv(V) glRasterPos(V)
#define glRasterPos2fv(V) glRasterPos(V)
#define glRasterPos2iv(V) glRasterPos(V)
#define glRasterPos2sv(V) glRasterPos(V)
#define glRasterPos3dv(V) glRasterPos(V)
#define glRasterPos3fv(V) glRasterPos(V)
#define glRasterPos3iv(V) glRasterPos(V)
#define glRasterPos3sv(V) glRasterPos(V)
#define glRasterPos4dv(V) glRasterPos(V)
#define glRasterPos4fv(V) glRasterPos(V)
#define glRasterPos4iv(V) glRasterPos(V)
#define glRasterPos4sv(V) glRasterPos(V)

#define glRotated(A,X,Y,Z) glRotate(A,X,Y,Z)
#define glRotatef(A,X,Y,Z) glRotate(A,X,Y,Z)

#define glScaled(X,Y,Z) glScale(X,Y,Z)
#define glScalef(X,Y,Z) glScale(X,Y,Z)

#define glTextCoord1d(S) glTextCoord(S)
#define glTextCoord1f(S) glTextCoord(S)
#define glTextCoord1i(S) glTextCoord(S)
#define glTextCoord1s(S) glTextCoord(S)

#define glTextCoord2d(S,T) glTextCoord(S,T)
#define glTextCoord2f(S,T) glTextCoord(S,T)
#define glTextCoord2i(S,T) glTextCoord(S,T)
#define glTextCoord2s(S,T) glTextCoord(S,T)

#define glTextCoord3d(S,T,R) glTextCoord(S,T,R)
#define glTextCoord3f(S,T,R) glTextCoord(S,T,R)
#define glTextCoord3i(S,T,R) glTextCoord(S,T,R)
#define glTextCoord3s(S,T,R) glTextCoord(S,T,R)

#define glTextCoord4d(S,T,R,Q) glTextCoord(S,T,R,Q)
#define glTextCoord4f(S,T,R,Q) glTextCoord(S,T,R,Q)
#define glTextCoord4i(S,T,R,Q) glTextCoord(S,T,R,Q)
#define glTextCoord4s(S,T,R,Q) glTextCoord(S,T,R,Q)

#define glTextCoord1dv(V) glTextCoord(V)
#define glTextCoord1fv(V) glTextCoord(V)
#define glTextCoord1iv(V) glTextCoord(V)
#define glTextCoord1sv(V) glTextCoord(V)
#define glTextCoord2dv(V) glTextCoord(V)
#define glTextCoord2fv(V) glTextCoord(V)
#define glTextCoord2iv(V) glTextCoord(V)
#define glTextCoord2sv(V) glTextCoord(V)
#define glTextCoord3dv(V) glTextCoord(V)
#define glTextCoord3fv(V) glTextCoord(V)
#define glTextCoord3iv(V) glTextCoord(V)
#define glTextCoord3sv(V) glTextCoord(V)
#define glTextCoord4dv(V) glTextCoord(V)
#define glTextCoord4fv(V) glTextCoord(V)
#define glTextCoord4iv(V) glTextCoord(V)
#define glTextCoord4sv(V) glTextCoord(V)

#define glTexEnvf(T,N,P) glTexEnv(T,N,P)
#define glTexEnvi(T,N,P) glTexEnv(T,N,P)
#define glTexEnvfv(T,N,P) glTexEnv(T,N,P)
#define glTexEnviv(T,N,P) glTexEnv(T,N,P)

#define glTexGend(C,N,P) glTexGen(C,N,P)
#define glTexGenf(C,N,P) glTexGen(C,N,P)
#define glTexGeni(C,N,P) glTexGen(C,N,P)
#define glTexGendv(C,N,P) glTexGen(C,N,P)
#define glTexGenfv(C,N,P) glTexGen(C,N,P)
#define glTexGeniv(C,N,P) glTexGen(C,N,P)

#define glTexParameterf(T,N,P) glTexParameter(T,N,P)
#define glTexParameteri(T,N,P) glTexParameter(T,N,P)
#define glTexParameterfn(T,N,P) glTexParameter(T,N,P)
#define glTexParameteriv(T,N,P) glTexParameter(T,N,P)

#define glTranslated(X,Y,Z) glTranslate(X,Y,Z)
#define glTranslatef(X,Y,Z) glTranslate(X,Y,Z)

#define glVertex2d(X,Y) glVertex(X,Y)
#define glVertex2f(X,Y) glVertex(X,Y)
#define glVertex2i(X,Y) glVertex(X,Y)
#define glVertex2s(X,Y) glVertex(X,Y)

#define glVertex3d(X,Y,Z) glVertex(X,Y,Z)
#define glVertex3f(X,Y,Z) glVertex(X,Y,Z)
#define glVertex3i(X,Y,Z) glVertex(X,Y,Z)
#define glVertex3s(X,Y,Z) glVertex(X,Y,Z)

#define glVertex4d(X,Y,Z,W) glVertex(X,Y,Z,W)
#define glVertex4f(X,Y,Z,W) glVertex(X,Y,Z,W)
#define glVertex4i(X,Y,Z,W) glVertex(X,Y,Z,W)
#define glVertex4s(X,Y,Z,W) glVertex(X,Y,Z,W)

#define glVertex2dv(V) glVertex(V)
#define glVertex2fv(V) glVertex(V)
#define glVertex2iv(V) glVertex(V)
#define glVertex2sv(V) glVertex(V)
#define glVertex3dv(V) glVertex(V)
#define glVertex3fv(V) glVertex(V)
#define glVertex3iv(V) glVertex(V)
#define glVertex3sv(V) glVertex(V)
#define glVertex4dv(V) glVertex(V)
#define glVertex4fv(V) glVertex(V)
#define glVertex4iv(V) glVertex(V)
#define glVertex4sv(V) glVertex(V)
