#!/bin/sh

#This can be 'sprsh' or 'wine'
REMOTE_METHOD=sprsh

# Choose 'rntcc' for Watcom or 'rntcl' for Microsoft VC++
# (Make sure VC++ is before Watcom in your path!)
CC=${CC-rntcl}

# Edit
NTHOST=${NTHOST-10.0.5.13}
NTDRIVE='k:'

# Edit
#NTHOST=10.0.5.10
#NTDRIVE='k:'

#NTHOST=localhost
#NTDRIVE='d:'

# What dir on the UNIX machine is on $NTDRIVE ?
# This variable MUST NOT end with a slash.
NTMOUNT=

# Use Simple Pike Remote SHell?
USE_SPRSH=yes

# Port for sprsh
NTPORT=4711

#These are only used if you use wine
watcom=D:\\CDROM
INCLUDE="$watcom\\H;$watcom\\H\\NT"

case "/$CC" in
  */rntcl)
    MSVC='j:\winshare\vc98'
    local='j:\winshare\local'
    REMOTE_VARIABLES="
path=$MSVC\\bin;
include=$MSVC\\Include;$local\\include
lib=$MSVC\\Lib;$local\\lib
"
    export REMOTE_VARIABLES
  ;;

  */rntcc)
    watcom='j:\winshare\WATCOM'
    local='j:\winshare\WATCOM\local'
    REMOTE_VARIABLES="
path=$watcom\\binnt;$watcom\\binw;
include=$watcom\\h;$local\\h
lib=$watcom\\lib386;$local\\lib
"
    export REMOTE_VARIABLES
  ;;
esac


# Don't edit

case /$0 in
  */init_nt)
    # We were executed we can find the path!
    base=`echo $0 | sed -e 's@/init_nt@@'`
    base=`(test "x$base" != "x" && cd $base ; /bin/pwd)`
  ;;

  *)
    # We were sourced, we cannot find the path...
    base=`pwd`
  ;;
esac

NT_TOOL_PATH=$base/tools

export NT_TOOL_PATH

if [ ! -d "$NT_TOOL_PATH" ]; then
  echo Unable to find NT tools!
  return
  exit
fi

case :$PATH: in
   *:$NT_TOOL_PATH:*) ;;
   *) PATH=$NT_TOOL_PATH:$PATH ;;
esac

NTTOOLS=$NT_TOOL_PATH/lib

if [ "x$NTMOUNT" = x ]; then
  MNTREPLACE=""
else
  MNTREPLACE="s@$NTMOUNT@@g
"
fi
IFS=' 	
'

export NTHOST NTDRIVE NTCC CC PATH NTTOOLS MNTREPLACE MNTREPLACE 
export NTPORT USE_SPRSH NTMOUNT IFS REMOTE_METHOD watcom INCLUDE
export NT_TOOL_PATH NTCOMPILER

case /$SHELL-$TERM in
   */bash-xterm)
     PROMPT_COMMAND="echo -n ]2\; $REMOTE_METHOD NT compile ]1\; rntcc"
     export PROMPT_COMMAND
   ;;
esac

case /$0 in
  */init_nt)
    case /$SHELL in
      */bash)
        exec $SHELL -rcfile $NT_TOOL_PATH/bash-fixup
      ;;
      *)
        exec $SHELL
      ;;
    esac
  ;;
esac
