#!/bin/sh

# Edit
NTHOST=10.0.4.10
NTDRIVE='j:'

# What dir on the UNIX machine is on $NTDRIVE ?
# This variable MUST NOT end with a slash.
NTMOUNT=

# Use Simple Pike Remote SHell?
USE_SPRSH=yes

# Port for sprsh
NTPORT=4711

# Don't edit

base=`pwd`

NP=$base/tools

case :$PATH: in
   *:$NP:*) ;;
   *) PATH=$NP:$PATH ;;
esac
CC=rntcc
NTTOOLS=$NP/lib
if [ "x$NTMOUNT" = x ]; then
  MNTREPLACE=""
else
  MNTREPLACE="s@$NTMOUNT@@g
"
fi

export NTHOST NTDRIVE NTCC CC PATH NTTOOLS MNTREPLACE MNTREPLACE NTPORT USE_SPRSH

case /$SHELL-$TERM in
   */bash-xterm)
     PROMPT_COMMAND="echo -n ]2\; Remote NT compile ]1\; rntcc"
     export PROMPT_COMMAND
   ;;
esac

case /$SHELL in
   */bash)
     PS1="NT $NTHOST \\$ "
     export PS1
   ;;
esac


case /$0 in
  */init_nt)
    exec $SHELL
  ;;
esac
