// Automatically generated by "doc-pikeref.pike" from "gnomecanvasre.pre".
// Do NOT edit.

//! Properties:
//! float x1
//! float x2
//! float y1
//! float y2
//!
//!

inherit Gnome2.CanvasShape;
//!

