// Automatically generated by "doc-pikeref.pike" from "gnomecanvasitem.pre".
// Do NOT edit.

//! This is the base class for all canvas items.  Canvas items are the drawing
//! elements of a Gnome2.Canvas.  Example items include lines, ellipses,
//! polygons, images, text, curves, and even arbitary GTK+ widgets.
//! 
//! Properties:
//! Gnome2.CanvasItem parent
//!
//!
//!  Signals:
//! @b{event@}
//!

inherit GTK2.Object;
//!

