// Automatically generated by "doc-pikeref.pike" from "gnomecanvaspixbuf.pre".
// Do NOT edit.

//! Properties:
//! int anchor
//! float height
//! int height-in-pixels
//! int height-set
//! GDK2.Pixbuf pixbuf
//! float width
//! int width-in-pixels
//! int width-set
//! float x
//! int x-in-pixels
//! float y
//! int y-in-pixels
//!
//!

inherit Gnome2.CanvasItem;
//!

