%!PS-Adobe-3.0 EPSF-3.0
%%Creator: Adobe Photoshop Version 6.0
%%Title: 22-photoshop-dcs-1.0.eps
%%CreationDate: Mon Mar 24 2003 17:05:43
%%BoundingBox: 0 0 1 1
%%HiResBoundingBox: 0 0 1 1
%%SuppressDotGainCompensation
%%EndComments
%%BeginProlog
%%EndProlog
%%BeginSetup
%%EndSetup
%ImageData: 1 1 8 1 0 1 1 "beginimage"
gsave % EPS gsave
40 dict begin
/_image systemdict /image get def
/_setgray systemdict /setgray get def
/_currentgray systemdict /currentgray get def
/_settransfer systemdict /settransfer get def
/_currenttransfer systemdict /currenttransfer get def
/blank 0 _currenttransfer exec
1 _currenttransfer exec eq def
/negative blank
{0 _currenttransfer exec 0.5 lt}
{0 _currenttransfer exec 1 _currenttransfer exec gt}
ifelse def
/inverted? negative def
/level2 systemdict /languagelevel known
{languagelevel 2 ge} {false} ifelse def
/level3 systemdict /languagelevel known
{languagelevel 3 ge} {false} ifelse def
gsave % Image Header gsave
/rows 1 def
/cols 1 def
1 1 scale
level2 {
/DeviceGray
setcolorspace currentdict /PhotoshopDuotoneColorSpace undef currentdict /PhotoshopDuotoneAltColorSpace undef } if
/picstr1 1 string def
/_rowpadstr 1 string def
/rawreaddata {currentfile exch readstring pop} def
/padreaddata { _topPad 0 gt       { /_topPad _topPad 1 sub def pop _rowpadstr }
			 { _subImageRows 0 gt { /_subImageRows _subImageRows 1 sub def
									dup _leftPad _picsubstr rawreaddata putinterval }
								  { pop _rowpadstr } ifelse } ifelse } def
/image2 level2 {/image load def} {{begin
Width Height BitsPerComponent ImageMatrix
/DataSource load image end} def} ifelse
/beginimage {
image2
} def
/readdata /rawreaddata load bind def
12 dict begin
/ImageType 1 def
/Width cols def
/Height rows def
/ImageMatrix [cols 0 0 rows neg 0 rows] def
/BitsPerComponent 8 def
/Decode [0 1] def
/DataSource {picstr1 readdata} def
currentdict end
%%BeginBinary:         13
beginimageK
%%EndBinary
grestore end % Image Trailer grestore
grestore % EPS grestore
