SRCDIR=@srcdir@
VPATH=@srcdir@:@srcdir@/../..:../..
PREFLAGS=$(DEFINES) -I. -I$(SRCDIR) -I$(SRCDIR)/../.. -I../..

SSLEAY_FLAGS=@SSLEAY_FLAGS@
CFLAGS=$(PREFLAGS) $(OTHERFLAGS) $(SSLEAY_FLAGS)

OBJS=ssleay.o

ssleay.a: $(OBJS)
	-rm -f ssleay.a
	ar cq ssleay.a $(OBJS)
	-@RANLIB@ ssleay.a
	echo >linker_options @LIBS@

clean:
	-rm -f *.o *.a

depend:
	gcc -MM $(PREFLAGS) $(SRCDIR)/*.c | $(TMP_BINDIR)/fixdepends.sh $(SRCDIR)
