SRCDIR=@srcdir@
VPATH=@srcdir@:@srcdir@/../..:../..
PREFLAGS=$(DEFINES) @DEFS@ -I. -I$(SRCDIR) -I$(SRCDIR)/../.. -I../.. @CPPFLAGS@

CFLAGS=$(PREFLAGS) $(OTHERFLAGS)

OBJS=ssleay.o

ssleay.a: $(OBJS)
	-rm -f ssleay.a
	ar cq ssleay.a $(OBJS)
	-@RANLIB@ ssleay.a
	echo >linker_options "@LDFLAGS@ @LIBS@"

clean:
	-rm -f *.o *.a

depend:
	gcc -MM $(PREFLAGS) $(SRCDIR)/*.c | $(TMP_BINDIR)/fixdepends.sh $(SRCDIR)

