SRCDIR=@srcdir@
VPATH=@srcdir@:@srcdir@/../..:../..
PREFLAGS=-I$(SRCDIR) -I$(SRCDIR)/../.. -I../..
CFLAGS=$(PREFLAGS) $(OTHERFLAGS) @DEFS@

FILES=pipe.o

pipe.a: $(FILES)
	-rm -f pipe.a
	ar cq pipe.a $(FILES)
	-@RANLIB@ pipe.a

clean:
	-rm -f *.o *.a

depend:
	gcc -MM $(PREFLAGS) $(SRCDIR)/*.c | $(FIXDEP) $(SRCDIR)
