#!/bin/sh
if test "$#" = "1"; then
  case "$1" in
    --cflags)
      echo
    ;;
    --libs)
      echo "" -lfreetype
    ;;
    *)
      echo Bad argument to rntfreetype-config: "$1". 1>&2
      exit 1
    ;;
  esac
else
  echo Bad arguments to rntfreetype-config. 1>&2
  exit 1
fi