#!/bin/sh

. $NTTOOLS

for a in "$@"
do
  case "$a" in
    --version)
      echo "1.2.13"
      exit 0
    ;;

    --cflags)
      #Funny story: Pike configure considers empty SDL_CFLAGS == fail
      echo "-D_DUMMY"
      exit 0
    ;;

    --libs)
      echo "-lsdl"
      exit 0
    ;;

    *)
      echo "Unknown option $a"
      exit 1
    ;;
   esac
done
