#!/bin/sh

. $NTTOOLS

S=
R=
M=
N=
V=
P=

for a in "$@"
do
  case "$a" in
    --version)
      echo "Fake NT uname version 1.1 by Fredrik Hubinette"
      exit 0
    ;;

    --help)
      echo "Usage: uname [-a] [-m] [-n] [-p] [-r] [-s] [-v]"
      exit 0
    ;;

    --all)  S=yes ; R=yes ; M=yes ; N=yes ; V=yes ; P=yes ;;
    --machine) M=yes ;;
    --nodename) N=yes ;;
    --sysname) S=yes ;;
    --processor) P=yes ;;
    --revision) R=yes ;;

    --*)
      echo "Unknown option $a"
      exit 1
    ;;

    -*)
      case "$a" in
        *m*) M=yes ;;
      esac

      case "$a" in
        *n*) N=yes ;;
      esac

      case "$a" in
        *p*) P=yes ;;
      esac

      case "$a" in
        *s*) S=yes ;;
      esac

      case "$a" in
        *r*) R=yes ;;
      esac

      case "$a" in
        *v*) V=yes ;;
      esac

      case "$a" in
        *a*) M=yes ; N=yes ; S=yes ; V=yes ;;
      esac
    ;;
      
  esac
done

if [ X"$M$N$S$P$R$V" = X ]; then
  S=yes
fi

OUTPUT=

if [ X$S = Xyes ]; then
  OUTPUT="$OUTPUT `sprsh cmd /c ver | grep \\\[ | awk -F\[ '{print $1}'`"
fi

if [ X$N = Xyes ]; then
  OUTPUT="$OUTPUT $NTHOST"
fi

if [ X$R = Xyes ]; then
  OUTPUT="$OUTPUT `sprsh cmd /c ver | grep \\\[ | awk -F\\[ '{print $2}' | awk '{print $2}' | sed 's/\\]//'`"
fi

if [ X$V = Xyes ]; then
  OUTPUT="$OUTPUT `sprsh cmd /c ver | grep \\\[ | awk -F\\[ '{print $2}' | awk '{print $2}' | sed 's/\\]//'`"
fi

if [ $M$P = "" ]; then :; else
  # Workaround for XP64 DWIMing PROCESSOR_ARCHITECTURE...
  PROCESSOR_ARCHITECTURE="`getntenv PROCESSOR_IDENTIFIER|cut '-d ' -f1`"

  # PROCESSOR_IDENTIFIER is typically something like:
  #   "ia64 Family 7 Model 1 Stepping 5, GenuineIntel"
  # or
  #   "x86 Family 6 Model 7 Stepping 3, GenuineIntel"

  if [ $M = yes ]; then
    OUTPUT="$OUTPUT $PROCESSOR_ARCHITECTURE"
  fi
  
  if [ $P = yes ]; then
    OUTPUT="$OUTPUT $PROCESSOR_ARCHITECTURE"
  fi
fi

echo $OUTPUT

exit 0
