#!/bin/sh
#
# $Id: run_autoconfig,v 1.36 2003/02/06 17:06:12 grubba Exp $
#
# Bootstrap script

need_to_make_depend=no
prune_flag=""

case :$PATH: in
   */NT/tools:*)
      echo Stripping NT/tools from path temporarily...
      PATH=`echo :$PATH | sed 's@:[^:]*/NT/tools:@@g' | sed 's@^:@@'`
   ;;
esac

if test "x$1" = "x--no-recursion"; then
  prune_flag="-prune"
  shift
fi

if test "x$1" = "x" ; then
  base=`echo $0 | sed 's@[^/]*$@@g'`
  if test "x$base" != "x" ; then
    cd "$base"
  fi

  localdir=`pwd`
else
  cd "$1"

  localdir=`echo $0 | sed 's@[^/]*$@@g'`
  if test "x$localdir" = "x"; then
    localdir=`pwd`
  else
    localdir=`cd $localdir;pwd`
  fi
fi

autoconf=autoconf
autoheader=autoheader

autoconf_version="`\"$autoconf\" --version|head -1|awk '{ print $NF }'`"

extra_ac_args=""
extra_ah_args=""

if [ "`echo \"$autoconf_version\"|awk -F. '{ print $1 }'`" -ne "2" -o \
     "`echo \"$autoconf_version\"|awk -F. '{ print $2 }'`" -le "10" -o \
     "`echo \"$autoconf_version\"|awk -F. '{ print $2 }'`" -ge "50" ]; then
  if [ "`echo \"$autoconf_version\"|awk -F. '{ print $2 }'`" -le "51" ]; then
    # Autoconf 2.50 and 2.51 are seriously broken.
    echo "Autoconf version $autoconf_version is not supported." >&2
    echo >&2
    echo "Get and install autoconf 2.52 or later." >&2
    # Abort
    exit 1
  elif [ "`echo \"$autoconf_version\"|awk -F. '{ print $1 }'`" = "2" -a \
         "`echo \"$autoconf_version\"|awk -F. '{ print $2 }'`" -ge "53" ]; then
    echo "Warning: Autoconf 2.53 and later use parts written in Perl," >&2
    echo "         and are notoriously broken." >&2
    # NB: autoheader 2.53 is stupid, and has broken handling of warnings.
    #     1) The warning flags are not passed along to autoconf.
    #     2) The option --warnings is misspelled by missing the last 's'.
    extra_ac_args="-Wno-obsolete"
    extra_ah_args="-Wno-obsolete"
    # Attempt to kludge around Perl's stupid warnings about locale settings.
    LANGUAGE=C LC_CTYPE=C LANG=C export LANGUAGE LC_CTYPE LANG
    LC_MONETARY=C LC_NUMERIC=C export LC_MONETARY LC_NUMERIC
    LC_MESSAGES=C LC_COLLATE=C export LC_MESSAGES LC_COLLATE
    LC_TIME=C LC_ALL=C export LC_TIME LC_ALL
  fi;
else :; fi

autoheader_version="`\"$autoconf\" --version|head -1|awk '{ print $NF }'`"

if [ "x$autoconf_version" != "x$autoheader_version" ]; then
  echo "$autoheader version ($autoheader_version) differs from $autoconf version ($autoconf_version)" >&2
  # Abort
  exit 1
else :; fi

IFS=''
( find . -follow -type d -print $prune_flag || find . -type d -print $prune_flag ) |egrep -v '/(CVS)|(RCS)|(test-install)$'| while read dir; do

  if [ -f $dir/Makefile.am -a -f $dir/configure.in ]; then
    # aclocal needs to be run before autoconf
    echo "Running aclocal in $dir"
    (cd $dir ; aclocal )
    echo "Running automake in $dir"
    (cd $dir ; automake )
  fi

  if [ -f $dir/configure.in ] && grep AC_CONFIG_HEADER $dir/configure.in >/dev/null; then
    echo "Running $autoheader in $dir"
    ( cd $dir ; "$autoheader" $extra_ah_args && echo foo >stamp-h.in )
  fi

  if [ -f $dir/configure.in ]; then
    if grep AC_INIT $dir/configure.in >/dev/null; then
      echo "Running $autoconf in $dir"
      ( cd $dir ; "$autoconf" $extra_ac_args --localdir=$localdir )
    else
      echo "$dir seems to use Cygnus-configure."
    fi
  fi

  if [ -f $dir/Makefile.in -a ! -f $dir/dependencies ] && egrep @dependencies@ $dir/Makefile.in >/dev/null; then
    touch $dir/dependencies
    need_to_make_depend=yes
  fi
done

if test "x$need_to_make_depend" = "xyes" ; then
  echo You need to run \"make depend\" after \"configure\", and then \"configure\" again.
fi

exit 0
