// Automatically generated by "doc-pikeref.pike" from "gtkcellrendererprogress.pre".
// Do NOT edit.

//! Properties:
//! int orientation
//! int pulse
//! string text
//! float text-xalign
//! float text-yalign
//! int value
//!
//!

inherit GTK2.CellRenderer;
//!

protected void create( void props );
//! Create a new W(CellRendererProgress).
//!
//!
