// Automatically generated by "doc-pikeref.pike" from "gtkcellrendereraccel.pre".
// Do NOT edit.

//! Properties:
//! int accel-key
//! int accel-mode
//! int accel-mods
//! int keycode
//!
//!
//!  Signals:
//! @b{accel_cleared@}
//!
//! @b{accel_edited@}
//!

inherit GTK2.CellRendererText;
//!

protected void create( void props );
//! Create a new GTK2.CellRendererAccel.
//!
//!
