// Automatically generated by "doc-pikeref.pike" from "gtkcellrenderercombo.pre".
// Do NOT edit.

//! Properties:
//! int has-entry
//! GTK2.TreeModel model
//! int text-column
//!
//!

inherit GTK2.CellRendererText;
//!

protected void create( void props );
//! Creates a new W(CellRendererCombo).
//!
//!
