// Automatically generated by "doc-pikeref.pike" from "gtkcellrendererspin.pre".
// Do NOT edit.

//! Properties:
//! int digits
//! GTK2.Adjustment adjustment
//! float climb-rate
//!
//!

inherit GTK2.CellRendererText;
//!

protected void create( void props );
//! Create a new GTK2.CellRendererSpin.
//!
//!
