// Automatically generated by "doc-pikeref.pike" from "gtkdata.pre".
// Do NOT edit.

//! A class inherited by all objects used to store data (they are not widgets)
//!
//!
//!  Signals:
//! @b{disconnect@}
//!

inherit GTK2.Object;
//!

