// Automatically generated by "doc-pikeref.pike" from "gtkhseparator.pre".
// Do NOT edit.

//! Simply creates a horizontal separator. No bells or whistles.
//!@expr{ GTK2.Hseparator()->set_size_request(300,3)@}
//!@xml{<image>../images/gtk2_hseparator.png</image>@}
//!
//!
//!

inherit GTK2.Separator;
//!

protected void create( void props );
//! Used to create a new hseparator widget.
//!
//!
