// Automatically generated by "doc-pikeref.pike" from "gtkinvisible.pre".
// Do NOT edit.

//! An invisible container, useful, eh? :)
//! Properties:
//! GDK2.Screen screen
//!
//!

inherit GTK2.Widget;
//!

protected void create( void props );
//! Create a new invisible widget
//!
//!

GDK2.Screen get_screen( );
//! Gets the screen associated with this object.
//!
//!

GTK2.Invisible set_screen( GDK2.Screen screen );
//! Sets the screen where this object will be displayed.
//!
//!
