// Automatically generated by "doc-pikeref.pike" from "gtkkeywordlisttag.pre".
// Do NOT edit.

//!
//!
//!

inherit GTK2.SourceTag;
//!

protected void create( void id, void name, void keywords, void case_sensitive, void match_empty_string_at_beginning, void match_empty_string_at_end, void beginning_regex, void end_regex );
//! Creates a new keyword list tag object with the provided arguments.
//!
//!
