// Automatically generated by "doc-pikeref.pike" from "gtklinecommenttag.pre".
// Do NOT edit.

//!
//!
//!

inherit GTK2.SourceTag;
//!

protected void create( void id, void name, void pattern_start );
//! Creates a new line comment tag object with the provided arguments.
//!
//!
