// Automatically generated by "doc-pikeref.pike" from "gtkpatterntag.pre".
// Do NOT edit.

//!
//!
//!

inherit GTK2.SourceTag;
//!

protected void create( void id, void name, void pattern );
//! Creates a new pattern tag object with the provided arguments.
//!
//!
