// Automatically generated by "doc-pikeref.pike" from "gtkprintbackend.pre".
// Do NOT edit.

//!
//!
//!

inherit G.Object;
//!

GTK2.PrintBackend add_printer( GTK2.Printer printer );
//!
//!
//!

GTK2.Printer find_printer( string name );
//!
//!
//!

int printer_list_is_done( );
//!
//!
//!

GTK2.PrintBackend remove_printer( GTK2.Printer printer );
//!
//!
//!

GTK2.PrintBackend set_list_done( );
//!
//!
//!
