// Automatically generated by "doc-pikeref.pike" from "gtkprogress.pre".
// Do NOT edit.

//! Properties:
//! int activity-mode
//! int show-text
//! float text-xalign
//! float text-yalign
//!
//!

inherit GTK2.Widget;
//!

