// Automatically generated by "doc-pikeref.pike" from "gtkrecentchooserdialog.pre".
// Do NOT edit.

//!
//!
//!

inherit GTK2.Dialog;
//!

inherit GTK2.RecentChooser;
//!

protected void create( void title, void parent, void buttons, void manager );
//! Creates a new RecentChooserDialog.  Analogous to
//! GTK2.Dialog->create().
//!
//!
