// Automatically generated by "doc-pikeref.pike" from "gtkrecentchooserwidget.pre".
// Do NOT edit.

//!
//!
//!

inherit GTK2.Vbox;
//!

inherit GTK2.RecentChooser;
//!

protected void create( void props );
//! Create a new GTK2.RecentChooserWidget.
//!
//!
