// Automatically generated by "doc-pikeref.pike" from "gtkseparatormenuitem.pre".
// Do NOT edit.

//! A separator menu item.
//!
//!

inherit GTK2.MenuItem;
//!

protected void create( void props );
//! Create a new GTK2.SeparatorMenuItem.
//!
//!
