// Automatically generated by "doc-pikeref.pike" from "gtkstringtag.pre".
// Do NOT edit.

//!
//!
//!

inherit GTK2.SourceTag;
//!

protected void create( void id, void name, void pattern_start, void pattern_end, void end_at_line_end );
//! Creates a new string tag object with the provided arguments.
//!
//!
