// Automatically generated by "doc-pikeref.pike" from "gtkvolumebutton.pre".
// Do NOT edit.

//! Volume Button
//!
//!

inherit GTK2.ScaleButton;
//!

protected void create( void props );
//! Create a new W(VolumeButton).
//!
//!
