// Automatically generated by "doc-pikeref.pike" from "gtkvscrollbar.pre".
// Do NOT edit.

//! General documentation: See W(Scrollbar)
//!@expr{ GTK2.VScrollbar(GTK2.Adjustment())->set_size_request(15,60)@}
//!@xml{<image>../images/gtk2_vscrollbar.png</image>@}
//!
//!
//!

inherit GTK2.Scrollbar;
//!

protected void create( void pos_or_props );
//! Used to create a new vscrollbar widget.
//!
//!
